import type { Category, Prompt } from "@/types";

// ===== 完整分类体系 =====
// 基于 category.txt 和 category.html 整合的全面分类系统

export const categories: Category[] = [
  {
    id: "research-academic",
    name: "科研学术",
    slug: "research-academic",
    description:
      "选题与研究问题、文献综述、论文写作、投稿回复、基金申请等学术场景",
    icon: "Microscope",
    color: "bg-blue-100 text-blue-600",
    promptCount: 1250,
    subcategories: [
      {
        id: "topic-gap",
        name: "选题与研究问题（gap挖掘）",
        slug: "topic-gap",
        categoryId: "research-academic",
      },
      {
        id: "literature-review",
        name: "文献检索与综述",
        slug: "literature-review",
        categoryId: "research-academic",
      },
      {
        id: "research-design",
        name: "研究设计（变量、假设、方法）",
        slug: "research-design",
        categoryId: "research-academic",
      },
      {
        id: "experiment-simulation",
        name: "实验/仿真方案",
        slug: "experiment-simulation",
        categoryId: "research-academic",
      },
      {
        id: "data-visualization",
        name: "数据统计与可视化",
        slug: "data-visualization",
        categoryId: "research-academic",
      },
      {
        id: "paper-writing",
        name: "论文写作",
        slug: "paper-writing",
        categoryId: "research-academic",
      },
      {
        id: "submission-rebuttal",
        name: "投稿与审稿回复",
        slug: "submission-rebuttal",
        categoryId: "research-academic",
      },
      {
        id: "academic-presentation",
        name: "学术展示（slide/答辩）",
        slug: "academic-presentation",
        categoryId: "research-academic",
      },
      {
        id: "grant-proposal",
        name: "基金/课题申请书",
        slug: "grant-proposal",
        categoryId: "research-academic",
      },
      {
        id: "academic-english",
        name: "学术英语（润色、摘要）",
        slug: "academic-english",
        categoryId: "research-academic",
      },
    ],
  },
  {
    id: "video-creation",
    name: "视频创作",
    slug: "video-creation",
    description: "选题、口播脚本、分镜、剪辑节奏、标题封面、直播带货、运营复盘",
    icon: "Video",
    color: "bg-red-100 text-red-600",
    promptCount: 980,
    subcategories: [
      {
        id: "topic-library",
        name: "选题库（热点/常青内容）",
        slug: "topic-library",
        categoryId: "video-creation",
      },
      {
        id: "script-structure",
        name: "脚本结构（起承转合）",
        slug: "script-structure",
        categoryId: "video-creation",
      },
      {
        id: "voiceover-script",
        name: "口播逐字稿",
        slug: "voiceover-script",
        categoryId: "video-creation",
      },
      {
        id: "storyboard",
        name: "分镜与镜头清单",
        slug: "storyboard",
        categoryId: "video-creation",
      },
      {
        id: "editing-strategy",
        name: "剪辑策略（节奏点、B-roll）",
        slug: "editing-strategy",
        categoryId: "video-creation",
      },
      {
        id: "subtitle",
        name: "字幕（断句、双语）",
        slug: "subtitle",
        categoryId: "video-creation",
      },
      {
        id: "cover-title",
        name: "封面与标题",
        slug: "cover-title",
        categoryId: "video-creation",
      },
      {
        id: "platform-operation",
        name: "平台运营",
        slug: "platform-operation",
        categoryId: "video-creation",
      },
      {
        id: "live-commerce",
        name: "直播带货",
        slug: "live-commerce",
        categoryId: "video-creation",
      },
      {
        id: "video-review",
        name: "复盘（数据解读）",
        slug: "video-review",
        categoryId: "video-creation",
      },
    ],
  },
  {
    id: "data-analysis",
    name: "数据分析",
    slug: "data-analysis",
    description:
      "埋点口径、数据清洗、EDA探索、指标体系、A/B实验、预测建模、分析写作",
    icon: "BarChart",
    color: "bg-green-100 text-green-600",
    promptCount: 856,
    subcategories: [
      {
        id: "data-acquisition",
        name: "数据获取（埋点、口径）",
        slug: "data-acquisition",
        categoryId: "data-analysis",
      },
      {
        id: "data-cleaning",
        name: "数据清洗",
        slug: "data-cleaning",
        categoryId: "data-analysis",
      },
      {
        id: "eda-exploration",
        name: "EDA探索",
        slug: "eda-exploration",
        categoryId: "data-analysis",
      },
      {
        id: "metrics-system",
        name: "指标体系",
        slug: "metrics-system",
        categoryId: "data-analysis",
      },
      {
        id: "visualization-report",
        name: "可视化与报表",
        slug: "visualization-report",
        categoryId: "data-analysis",
      },
      {
        id: "ab-experiment",
        name: "A/B实验分析",
        slug: "ab-experiment",
        categoryId: "data-analysis",
      },
      {
        id: "prediction-modeling",
        name: "预测与建模",
        slug: "prediction-modeling",
        categoryId: "data-analysis",
      },
      {
        id: "text-nlp",
        name: "文本/NLP分析",
        slug: "text-nlp",
        categoryId: "data-analysis",
      },
      {
        id: "attribution-analysis",
        name: "归因分析",
        slug: "attribution-analysis",
        categoryId: "data-analysis",
      },
      {
        id: "analysis-writing",
        name: "分析写作",
        slug: "analysis-writing",
        categoryId: "data-analysis",
      },
    ],
  },
  {
    id: "copywriting",
    name: "文案写作",
    slug: "copywriting",
    description:
      "品牌Slogan、新媒体推文、广告创意、SEO文章、产品文案、PR稿、演讲稿",
    icon: "PenTool",
    color: "bg-purple-100 text-purple-600",
    promptCount: 1450,
    subcategories: [
      {
        id: "brand-slogan",
        name: "品牌Slogan/定位语",
        slug: "brand-slogan",
        categoryId: "copywriting",
      },
      {
        id: "social-media",
        name: "新媒体推文",
        slug: "social-media",
        categoryId: "copywriting",
      },
      {
        id: "ad-creative",
        name: "广告创意",
        slug: "ad-creative",
        categoryId: "copywriting",
      },
      {
        id: "seo-article",
        name: "SEO文章",
        slug: "seo-article",
        categoryId: "copywriting",
      },
      {
        id: "product-copy",
        name: "产品文案",
        slug: "product-copy",
        categoryId: "copywriting",
      },
      {
        id: "pr-news",
        name: "PR稿/新闻稿",
        slug: "pr-news",
        categoryId: "copywriting",
      },
      {
        id: "speech-script",
        name: "演讲稿/主持稿",
        slug: "speech-script",
        categoryId: "copywriting",
      },
      {
        id: "business-email",
        name: "商务邮件/私信话术",
        slug: "business-email",
        categoryId: "copywriting",
      },
      {
        id: "course-copy",
        name: "课程/知识付费文案",
        slug: "course-copy",
        categoryId: "copywriting",
      },
      {
        id: "summary-report",
        name: "复盘/总结/周报",
        slug: "summary-report",
        categoryId: "copywriting",
      },
    ],
  },
  {
    id: "software-development",
    name: "程序开发",
    slug: "software-development",
    description:
      "需求澄清、架构设计、代码生成、测试、Debug、性能优化、API文档、DevOps",
    icon: "Code",
    color: "bg-indigo-100 text-indigo-600",
    promptCount: 1120,
    subcategories: [
      {
        id: "requirement-clarify",
        name: "需求澄清（用户故事）",
        slug: "requirement-clarify",
        categoryId: "software-development",
      },
      {
        id: "architecture-design",
        name: "架构设计",
        slug: "architecture-design",
        categoryId: "software-development",
      },
      {
        id: "code-generation",
        name: "代码生成（脚手架、模板）",
        slug: "code-generation",
        categoryId: "software-development",
      },
      {
        id: "unit-testing",
        name: "单元测试/测试用例",
        slug: "unit-testing",
        categoryId: "software-development",
      },
      {
        id: "debug-troubleshoot",
        name: "Debug与报错定位",
        slug: "debug-troubleshoot",
        categoryId: "software-development",
      },
      {
        id: "performance-optimization",
        name: "性能优化",
        slug: "performance-optimization",
        categoryId: "software-development",
      },
      {
        id: "api-documentation",
        name: "API设计与文档",
        slug: "api-documentation",
        categoryId: "software-development",
      },
      {
        id: "database-design",
        name: "数据库设计",
        slug: "database-design",
        categoryId: "software-development",
      },
      {
        id: "devops-deployment",
        name: "DevOps（CI/CD、容器）",
        slug: "devops-deployment",
        categoryId: "software-development",
      },
      {
        id: "security-auth",
        name: "安全（鉴权、漏洞）",
        slug: "security-auth",
        categoryId: "software-development",
      },
    ],
  },
  {
    id: "marketing",
    name: "市场营销",
    slug: "marketing",
    description:
      "市场调研、用户画像、品牌策略、内容营销、投放、SEO/SEM、公关传播",
    icon: "Megaphone",
    color: "bg-orange-100 text-orange-600",
    promptCount: 890,
    subcategories: [
      {
        id: "market-research",
        name: "市场调研",
        slug: "market-research",
        categoryId: "marketing",
      },
      {
        id: "user-persona",
        name: "用户画像/细分",
        slug: "user-persona",
        categoryId: "marketing",
      },
      {
        id: "brand-strategy",
        name: "品牌策略",
        slug: "brand-strategy",
        categoryId: "marketing",
      },
      {
        id: "content-marketing",
        name: "内容营销",
        slug: "content-marketing",
        categoryId: "marketing",
      },
      {
        id: "ad-placement",
        name: "投放（素材、落地页）",
        slug: "ad-placement",
        categoryId: "marketing",
      },
      {
        id: "seo-sem",
        name: "SEO/SEM",
        slug: "seo-sem",
        categoryId: "marketing",
      },
      {
        id: "social-operation",
        name: "社媒运营",
        slug: "social-operation",
        categoryId: "marketing",
      },
      {
        id: "pr-communication",
        name: "公关传播",
        slug: "pr-communication",
        categoryId: "marketing",
      },
      {
        id: "channel-cooperation",
        name: "渠道合作",
        slug: "channel-cooperation",
        categoryId: "marketing",
      },
      {
        id: "competitor-analysis",
        name: "竞品分析",
        slug: "competitor-analysis",
        categoryId: "marketing",
      },
    ],
  },
  {
    id: "product-management",
    name: "产品管理",
    slug: "product-management",
    description:
      "用户研究、需求管理、PRD与原型、版本规划、指标设计、增长策略、复盘机制",
    icon: "Briefcase",
    color: "bg-teal-100 text-teal-600",
    promptCount: 670,
    subcategories: [
      {
        id: "user-research",
        name: "用户研究",
        slug: "user-research",
        categoryId: "product-management",
      },
      {
        id: "requirement-management",
        name: "需求管理",
        slug: "requirement-management",
        categoryId: "product-management",
      },
      {
        id: "prd-prototype",
        name: "PRD与原型",
        slug: "prd-prototype",
        categoryId: "product-management",
      },
      {
        id: "version-planning",
        name: "版本规划",
        slug: "version-planning",
        categoryId: "product-management",
      },
      {
        id: "metrics-design",
        name: "指标设计",
        slug: "metrics-design",
        categoryId: "product-management",
      },
      {
        id: "growth-strategy",
        name: "增长策略",
        slug: "growth-strategy",
        categoryId: "product-management",
      },
      {
        id: "pricing-monetization",
        name: "定价与商业化",
        slug: "pricing-monetization",
        categoryId: "product-management",
      },
      {
        id: "launch-plan",
        name: "上线计划",
        slug: "launch-plan",
        categoryId: "product-management",
      },
      {
        id: "cross-team",
        name: "跨部门协同",
        slug: "cross-team",
        categoryId: "product-management",
      },
      {
        id: "product-review",
        name: "复盘",
        slug: "product-review",
        categoryId: "product-management",
      },
    ],
  },
  {
    id: "design-creative",
    name: "设计创意",
    slug: "design-creative",
    description:
      "品牌视觉、UI/UX、设计系统、海报物料、插画IP、动效包装、数据可视化设计",
    icon: "Palette",
    color: "bg-pink-100 text-pink-600",
    promptCount: 780,
    subcategories: [
      {
        id: "brand-visual",
        name: "品牌视觉（VI规范）",
        slug: "brand-visual",
        categoryId: "design-creative",
      },
      {
        id: "ui-design",
        name: "UI界面",
        slug: "ui-design",
        categoryId: "design-creative",
      },
      {
        id: "ux-experience",
        name: "UX体验",
        slug: "ux-experience",
        categoryId: "design-creative",
      },
      {
        id: "design-system",
        name: "设计系统",
        slug: "design-system",
        categoryId: "design-creative",
      },
      {
        id: "poster-kv",
        name: "海报/平面KV",
        slug: "poster-kv",
        categoryId: "design-creative",
      },
      {
        id: "illustration-ip",
        name: "插画与IP",
        slug: "illustration-ip",
        categoryId: "design-creative",
      },
      {
        id: "motion-graphics",
        name: "动效/视频包装",
        slug: "motion-graphics",
        categoryId: "design-creative",
      },
      {
        id: "3d-space",
        name: "3D与空间",
        slug: "3d-space",
        categoryId: "design-creative",
      },
      {
        id: "data-viz-design",
        name: "数据可视化设计",
        slug: "data-viz-design",
        categoryId: "design-creative",
      },
      {
        id: "design-review",
        name: "提案与评审",
        slug: "design-review",
        categoryId: "design-creative",
      },
    ],
  },
  {
    id: "education-training",
    name: "教育培训",
    slug: "education-training",
    description:
      "课程大纲、教案讲义、PPT脚本、题库测验、学习计划、批改反馈、教研迭代",
    icon: "BookOpen",
    color: "bg-yellow-100 text-yellow-600",
    promptCount: 920,
    subcategories: [
      {
        id: "course-outline",
        name: "课程大纲",
        slug: "course-outline",
        categoryId: "education-training",
      },
      {
        id: "lesson-plan",
        name: "教案/讲义",
        slug: "lesson-plan",
        categoryId: "education-training",
      },
      {
        id: "ppt-script",
        name: "PPT脚本",
        slug: "ppt-script",
        categoryId: "education-training",
      },
      {
        id: "quiz-bank",
        name: "题库与测验",
        slug: "quiz-bank",
        categoryId: "education-training",
      },
      {
        id: "learning-plan",
        name: "学习计划",
        slug: "learning-plan",
        categoryId: "education-training",
      },
      {
        id: "grading-feedback",
        name: "批改与反馈",
        slug: "grading-feedback",
        categoryId: "education-training",
      },
      {
        id: "classroom-interaction",
        name: "课堂互动",
        slug: "classroom-interaction",
        categoryId: "education-training",
      },
      {
        id: "teaching-research",
        name: "教研与迭代",
        slug: "teaching-research",
        categoryId: "education-training",
      },
      {
        id: "education-operation",
        name: "教务运营",
        slug: "education-operation",
        categoryId: "education-training",
      },
      {
        id: "certification-exam",
        name: "证书/考试辅导",
        slug: "certification-exam",
        categoryId: "education-training",
      },
    ],
  },
  {
    id: "ecommerce",
    name: "电商运营",
    slug: "ecommerce",
    description:
      "选品人群、商品标题、详情页、活动策划、广告投放、直播运营、数据分析",
    icon: "ShoppingBag",
    color: "bg-cyan-100 text-cyan-600",
    promptCount: 650,
    subcategories: [
      {
        id: "product-selection",
        name: "选品与人群",
        slug: "product-selection",
        categoryId: "ecommerce",
      },
      {
        id: "product-title",
        name: "商品标题/卖点",
        slug: "product-title",
        categoryId: "ecommerce",
      },
      {
        id: "detail-page",
        name: "详情页结构",
        slug: "detail-page",
        categoryId: "ecommerce",
      },
      {
        id: "event-planning",
        name: "活动策划",
        slug: "event-planning",
        categoryId: "ecommerce",
      },
      {
        id: "ecom-advertising",
        name: "广告投放",
        slug: "ecom-advertising",
        categoryId: "ecommerce",
      },
      {
        id: "live-operation",
        name: "直播运营",
        slug: "live-operation",
        categoryId: "ecommerce",
      },
      {
        id: "store-decoration",
        name: "店铺装修",
        slug: "store-decoration",
        categoryId: "ecommerce",
      },
      {
        id: "ecom-data",
        name: "数据分析",
        slug: "ecom-data",
        categoryId: "ecommerce",
      },
      {
        id: "supply-chain",
        name: "供应链",
        slug: "supply-chain",
        categoryId: "ecommerce",
      },
      {
        id: "customer-service",
        name: "客服与评价",
        slug: "customer-service",
        categoryId: "ecommerce",
      },
    ],
  },
  {
    id: "health-medical",
    name: "健康医疗",
    slug: "health-medical",
    description:
      "健康科普、医学文献速读、临床文书、患教材料、医院运营、医疗数据分析",
    icon: "Heart",
    color: "bg-rose-100 text-rose-600",
    promptCount: 540,
    subcategories: [
      {
        id: "health-science",
        name: "健康科普内容",
        slug: "health-science",
        categoryId: "health-medical",
      },
      {
        id: "medical-literature",
        name: "医学文献速读",
        slug: "medical-literature",
        categoryId: "health-medical",
      },
      {
        id: "clinical-document",
        name: "临床/护理文书",
        slug: "clinical-document",
        categoryId: "health-medical",
      },
      {
        id: "patient-education",
        name: "患教材料",
        slug: "patient-education",
        categoryId: "health-medical",
      },
      {
        id: "hospital-operation",
        name: "医院运营",
        slug: "hospital-operation",
        categoryId: "health-medical",
      },
      {
        id: "medical-data",
        name: "医疗数据分析",
        slug: "medical-data",
        categoryId: "health-medical",
      },
      {
        id: "drug-info",
        name: "药品信息整理",
        slug: "drug-info",
        categoryId: "health-medical",
      },
      {
        id: "patient-communication",
        name: "医患沟通模板",
        slug: "patient-communication",
        categoryId: "health-medical",
      },
      {
        id: "compliance-privacy",
        name: "合规与隐私提示",
        slug: "compliance-privacy",
        categoryId: "health-medical",
      },
    ],
  },
  {
    id: "music-art",
    name: "音乐艺术",
    slug: "music-art",
    description:
      "作曲灵感、和声编配、歌词创作、练习计划、乐理学习、录音混音、演出策划",
    icon: "Music",
    color: "bg-violet-100 text-violet-600",
    promptCount: 430,
    subcategories: [
      {
        id: "composition-theme",
        name: "作曲灵感与主题",
        slug: "composition-theme",
        categoryId: "music-art",
      },
      {
        id: "harmony-arrangement",
        name: "和声走向/编配",
        slug: "harmony-arrangement",
        categoryId: "music-art",
      },
      {
        id: "lyrics-writing",
        name: "歌词创作",
        slug: "lyrics-writing",
        categoryId: "music-art",
      },
      {
        id: "practice-plan",
        name: "练习计划",
        slug: "practice-plan",
        categoryId: "music-art",
      },
      {
        id: "music-theory",
        name: "乐理学习",
        slug: "music-theory",
        categoryId: "music-art",
      },
      {
        id: "recording-mixing",
        name: "录音/混音思路",
        slug: "recording-mixing",
        categoryId: "music-art",
      },
      {
        id: "performance-planning",
        name: "演出策划",
        slug: "performance-planning",
        categoryId: "music-art",
      },
      {
        id: "music-marketing",
        name: "音乐营销",
        slug: "music-marketing",
        categoryId: "music-art",
      },
      {
        id: "copyright-distribution",
        name: "版权与发行",
        slug: "copyright-distribution",
        categoryId: "music-art",
      },
    ],
  },
  {
    id: "sales-business",
    name: "商务销售",
    slug: "sales-business",
    description:
      "线索开发、销售SOP、方案报价、演示路演、客户画像、渠道合作、复盘培训",
    icon: "TrendingUp",
    color: "bg-amber-100 text-amber-600",
    promptCount: 560,
    subcategories: [
      {
        id: "lead-development",
        name: "线索开发",
        slug: "lead-development",
        categoryId: "sales-business",
      },
      {
        id: "sales-sop",
        name: "销售SOP",
        slug: "sales-sop",
        categoryId: "sales-business",
      },
      {
        id: "proposal-quotation",
        name: "方案/报价",
        slug: "proposal-quotation",
        categoryId: "sales-business",
      },
      {
        id: "demo-roadshow",
        name: "演示与路演",
        slug: "demo-roadshow",
        categoryId: "sales-business",
      },
      {
        id: "customer-profile",
        name: "客户画像与分层",
        slug: "customer-profile",
        categoryId: "sales-business",
      },
      {
        id: "bd-cooperation",
        name: "渠道合作",
        slug: "bd-cooperation",
        categoryId: "sales-business",
      },
      {
        id: "sales-training",
        name: "复盘与培训",
        slug: "sales-training",
        categoryId: "sales-business",
      },
    ],
  },
  {
    id: "customer-success",
    name: "客服支持",
    slug: "customer-success",
    description:
      "工单回复、FAQ知识库、投诉处理、NPS提升、用户教育、续费挽留、质检规范",
    icon: "Headphones",
    color: "bg-emerald-100 text-emerald-600",
    promptCount: 420,
    subcategories: [
      {
        id: "ticket-reply",
        name: "工单回复模板",
        slug: "ticket-reply",
        categoryId: "customer-success",
      },
      {
        id: "faq-knowledge",
        name: "FAQ/知识库",
        slug: "faq-knowledge",
        categoryId: "customer-success",
      },
      {
        id: "complaint-handling",
        name: "投诉处理与安抚",
        slug: "complaint-handling",
        categoryId: "customer-success",
      },
      {
        id: "nps-improvement",
        name: "NPS/满意度提升",
        slug: "nps-improvement",
        categoryId: "customer-success",
      },
      {
        id: "user-onboarding",
        name: "用户教育",
        slug: "user-onboarding",
        categoryId: "customer-success",
      },
      {
        id: "renewal-retention",
        name: "续费/流失挽回",
        slug: "renewal-retention",
        categoryId: "customer-success",
      },
      {
        id: "quality-inspection",
        name: "质检与话术规范",
        slug: "quality-inspection",
        categoryId: "customer-success",
      },
    ],
  },
  {
    id: "human-resources",
    name: "人力资源",
    slug: "human-resources",
    description: "JD撰写、简历筛选、面试题库、胜任力模型、绩效OKR、培训体系",
    icon: "Users",
    color: "bg-sky-100 text-sky-600",
    promptCount: 380,
    subcategories: [
      {
        id: "jd-writing",
        name: "JD撰写与优化",
        slug: "jd-writing",
        categoryId: "human-resources",
      },
      {
        id: "resume-interview",
        name: "简历筛选与面试题库",
        slug: "resume-interview",
        categoryId: "human-resources",
      },
      {
        id: "competency-model",
        name: "胜任力模型",
        slug: "competency-model",
        categoryId: "human-resources",
      },
      {
        id: "offer-negotiation",
        name: "Offer沟通与谈薪",
        slug: "offer-negotiation",
        categoryId: "human-resources",
      },
      {
        id: "onboarding-offboarding",
        name: "入职/离职流程",
        slug: "onboarding-offboarding",
        categoryId: "human-resources",
      },
      {
        id: "performance-okr",
        name: "绩效/OKR",
        slug: "performance-okr",
        categoryId: "human-resources",
      },
      {
        id: "hr-training",
        name: "培训体系",
        slug: "hr-training",
        categoryId: "human-resources",
      },
    ],
  },
  {
    id: "finance-accounting",
    name: "财务会计",
    slug: "finance-accounting",
    description:
      "预算编制、成本分析、财务报表、对账报销、现金流管理、经营分析、内控流程",
    icon: "Calculator",
    color: "bg-lime-100 text-lime-600",
    promptCount: 340,
    subcategories: [
      {
        id: "budget-forecast",
        name: "预算编制与预测",
        slug: "budget-forecast",
        categoryId: "finance-accounting",
      },
      {
        id: "cost-analysis",
        name: "成本/毛利分析",
        slug: "cost-analysis",
        categoryId: "finance-accounting",
      },
      {
        id: "financial-report",
        name: "财务报表解读",
        slug: "financial-report",
        categoryId: "finance-accounting",
      },
      {
        id: "reconciliation",
        name: "对账与报销规范",
        slug: "reconciliation",
        categoryId: "finance-accounting",
      },
      {
        id: "cashflow-management",
        name: "现金流管理",
        slug: "cashflow-management",
        categoryId: "finance-accounting",
      },
      {
        id: "business-analysis",
        name: "经营分析",
        slug: "business-analysis",
        categoryId: "finance-accounting",
      },
      {
        id: "internal-control",
        name: "内控流程",
        slug: "internal-control",
        categoryId: "finance-accounting",
      },
    ],
  },
  {
    id: "legal-compliance",
    name: "法务合规",
    slug: "legal-compliance",
    description: "合同条款、隐私合规、劳动用工、知识产权、风险评估、争议处理",
    icon: "Scale",
    color: "bg-slate-100 text-slate-600",
    promptCount: 290,
    subcategories: [
      {
        id: "contract-terms",
        name: "合同条款要点",
        slug: "contract-terms",
        categoryId: "legal-compliance",
      },
      {
        id: "privacy-compliance",
        name: "隐私与数据合规",
        slug: "privacy-compliance",
        categoryId: "legal-compliance",
      },
      {
        id: "labor-compliance",
        name: "劳动用工合规",
        slug: "labor-compliance",
        categoryId: "legal-compliance",
      },
      {
        id: "ip-protection",
        name: "知识产权",
        slug: "ip-protection",
        categoryId: "legal-compliance",
      },
      {
        id: "risk-assessment",
        name: "风险评估与培训",
        slug: "risk-assessment",
        categoryId: "legal-compliance",
      },
      {
        id: "dispute-handling",
        name: "争议处理",
        slug: "dispute-handling",
        categoryId: "legal-compliance",
      },
    ],
  },
  {
    id: "project-management",
    name: "项目管理",
    slug: "project-management",
    description:
      "项目计划、会议体系、跨部门协作、复盘机制、流程标准化、质量管理",
    icon: "ClipboardList",
    color: "bg-stone-100 text-stone-600",
    promptCount: 450,
    subcategories: [
      {
        id: "project-plan",
        name: "项目计划（WBS、里程碑）",
        slug: "project-plan",
        categoryId: "project-management",
      },
      {
        id: "meeting-system",
        name: "会议体系",
        slug: "meeting-system",
        categoryId: "project-management",
      },
      {
        id: "cross-department",
        name: "跨部门协作",
        slug: "cross-department",
        categoryId: "project-management",
      },
      {
        id: "retrospective",
        name: "复盘机制",
        slug: "retrospective",
        categoryId: "project-management",
      },
      {
        id: "process-sop",
        name: "流程标准化",
        slug: "process-sop",
        categoryId: "project-management",
      },
      {
        id: "quality-management",
        name: "质量管理",
        slug: "quality-management",
        categoryId: "project-management",
      },
      {
        id: "vendor-management",
        name: "供应商管理",
        slug: "vendor-management",
        categoryId: "project-management",
      },
    ],
  },
  {
    id: "strategy-consulting",
    name: "战略咨询",
    slug: "strategy-consulting",
    description:
      "行业研究、竞品拆解、商业模式、市场进入策略、定价策略、战略汇报",
    icon: "Lightbulb",
    color: "bg-fuchsia-100 text-fuchsia-600",
    promptCount: 320,
    subcategories: [
      {
        id: "industry-research",
        name: "行业研究框架",
        slug: "industry-research",
        categoryId: "strategy-consulting",
      },
      {
        id: "competitor-teardown",
        name: "竞品拆解",
        slug: "competitor-teardown",
        categoryId: "strategy-consulting",
      },
      {
        id: "business-model",
        name: "商业模式",
        slug: "business-model",
        categoryId: "strategy-consulting",
      },
      {
        id: "gtm-strategy",
        name: "市场进入策略",
        slug: "gtm-strategy",
        categoryId: "strategy-consulting",
      },
      {
        id: "pricing-strategy",
        name: "定价策略",
        slug: "pricing-strategy",
        categoryId: "strategy-consulting",
      },
      {
        id: "strategy-report",
        name: "战略汇报",
        slug: "strategy-report",
        categoryId: "strategy-consulting",
      },
    ],
  },
  {
    id: "growth-operation",
    name: "运营增长",
    slug: "growth-operation",
    description: "拉新获客、激活留存、变现策略、A/B实验、增长数据看板",
    icon: "Rocket",
    color: "bg-red-100 text-red-600",
    promptCount: 480,
    subcategories: [
      {
        id: "acquisition",
        name: "拉新（投放、裂变）",
        slug: "acquisition",
        categoryId: "growth-operation",
      },
      {
        id: "activation",
        name: "激活（新手引导）",
        slug: "activation",
        categoryId: "growth-operation",
      },
      {
        id: "retention",
        name: "留存（召回策略）",
        slug: "retention",
        categoryId: "growth-operation",
      },
      {
        id: "monetization",
        name: "变现（付费墙）",
        slug: "monetization",
        categoryId: "growth-operation",
      },
      {
        id: "growth-experiment",
        name: "A/B实验",
        slug: "growth-experiment",
        categoryId: "growth-operation",
      },
      {
        id: "growth-dashboard",
        name: "增长数据看板",
        slug: "growth-dashboard",
        categoryId: "growth-operation",
      },
    ],
  },
  {
    id: "translation-localization",
    name: "翻译本地化",
    slug: "translation-localization",
    description:
      "中英互译、本地化改写、字幕翻译、术语库、多语言客服、多语言营销",
    icon: "Globe",
    color: "bg-blue-100 text-blue-600",
    promptCount: 360,
    subcategories: [
      {
        id: "translation-polish",
        name: "中英互译/润色",
        slug: "translation-polish",
        categoryId: "translation-localization",
      },
      {
        id: "localization",
        name: "本地化改写",
        slug: "localization",
        categoryId: "translation-localization",
      },
      {
        id: "subtitle-translation",
        name: "字幕翻译与时间轴",
        slug: "subtitle-translation",
        categoryId: "translation-localization",
      },
      {
        id: "terminology",
        name: "术语库/风格指南",
        slug: "terminology",
        categoryId: "translation-localization",
      },
      {
        id: "multilingual-cs",
        name: "多语言客服话术",
        slug: "multilingual-cs",
        categoryId: "translation-localization",
      },
      {
        id: "multilingual-marketing",
        name: "多语言营销文案",
        slug: "multilingual-marketing",
        categoryId: "translation-localization",
      },
    ],
  },
];

// 获取分类图标映射
export const getCategoryIcon = (iconName: string) => iconName;

// 根据ID获取分类
export function getCategoryById(id: string): Category | undefined {
  return categories.find((c) => c.id === id);
}

// 根据slug获取分类
export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

// 获取所有子分类
export function getAllSubcategories() {
  return categories.flatMap((c) => c.subcategories);
}
